name: test

on:
  push:
    branches:
      - main
      
jobs:
  app-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel

    steps:
    - uses: actions/checkout@v2

   # dockerコンテナを起動
    - name: docker-compose up
      run: docker-compose up -d --build

    - name: Copy Environment File
      run: docker-compose exec -T app cp .env.example .env

    - name: Install Dependencies
      run: docker-compose exec -T app composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: docker-compose exec -T app php artisan key:generate

    ## マイグレーション
    - name: migration
      run: docker-compose exec -T app php artisan migrate

    ## test実行
    - name: Execute tests
      run: docker-compose exec -T app php artisan test

